import { Ionicons } from '@expo/vector-icons';
import { useLocalSearchParams, useRouter } from 'expo-router';
import React from 'react';
import {
  Pressable,
  ScrollView,
  Share,
  StyleSheet,
  Text,
  View,
} from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Card } from '@/components/ui/Card';
import { Skeleton, SkeletonCard } from '@/components/ui/Skeleton';
import { Colors, Radius, Spacing, Typography } from '@/constants/theme';
import { useZakatRecords } from '@/lib/hooks/useZakat';
import { formatGBP } from '@/lib/utils/currency';
import { formatDate } from '@/lib/utils/date';

export default function ZakatRecordDetailScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const insets = useSafeAreaInsets();
  const router = useRouter();

  const { data: records, isLoading } = useZakatRecords();
  const record = records?.find((r) => r.id === id);

  async function handleShare() {
    if (!record) return;
    const text = [
      `Meezan Zakat Record — ${record.hijri_year ?? formatDate(record.calculation_date)}`,
      ``,
      `Total Assets:    ${formatGBP(record.total_assets_gbp)}`,
      `Deductions:      ${formatGBP(record.total_deductions_gbp)}`,
      `Net Zakatable:   ${formatGBP(record.net_zakatable_gbp)}`,
      `Nisab (${record.nisab_type_used}): ${formatGBP(record.nisab_value_gbp)}`,
      ``,
      `Zakat Due:       ${formatGBP(record.zakat_due_gbp)}`,
      `Rate:            2.5%`,
      ``,
      `Generated by Meezan`,
    ].join('\n');

    await Share.share({ message: text, title: 'Zakat Record' });
  }

  return (
    <View style={[styles.container, { paddingTop: insets.top }]}>
      {/* Nav bar */}
      <View style={styles.navBar}>
        <Pressable onPress={() => router.back()} style={styles.backBtn}>
          <Ionicons name="chevron-back" size={22} color={Colors.textPrimary} />
          <Text style={styles.backLabel}>History</Text>
        </Pressable>
        <Text style={styles.navTitle}>Record</Text>
        {record ? (
          <Pressable onPress={handleShare} style={styles.shareBtn}>
            <Ionicons name="share-outline" size={20} color={Colors.primary} />
          </Pressable>
        ) : (
          <View style={{ width: 40 }} />
        )}
      </View>

      {isLoading ? (
        <ScrollView contentContainerStyle={styles.content}>
          <SkeletonCard lines={4} />
          <SkeletonCard lines={3} style={{ marginTop: Spacing.base }} />
          <View style={{ marginTop: Spacing.base, gap: Spacing.sm }}>
            <Skeleton width="40%" height={14} />
            <Skeleton width="100%" height={80} borderRadius={Radius.lg} />
          </View>
        </ScrollView>
      ) : !record ? (
        <View style={styles.notFound}>
          <Ionicons name="document-outline" size={48} color={Colors.textTertiary} />
          <Text style={styles.notFoundText}>Record not found</Text>
        </View>
      ) : (
        <ScrollView
          contentContainerStyle={[styles.content, { paddingBottom: insets.bottom + 24 }]}
          showsVerticalScrollIndicator={false}
        >
          {/* ── Hero ── */}
          <View style={styles.hero}>
            <View style={styles.heroIcon}>
              <Ionicons name="checkmark-circle" size={40} color={Colors.accent} />
            </View>
            <Text style={styles.heroYear}>{record.hijri_year ?? '—'}</Text>
            <Text style={styles.heroDate}>{formatDate(record.calculation_date)}</Text>
            <Text style={styles.heroAmount}>{formatGBP(record.zakat_due_gbp)}</Text>
            <Text style={styles.heroLabel}>Zakat Paid</Text>
          </View>

          {/* ── Calculation breakdown ── */}
          <Card padding="base" style={{ gap: Spacing.base }}>
            <Text style={styles.sectionTitle}>Calculation Breakdown</Text>

            <Row
              label="Total Assets"
              value={formatGBP(record.total_assets_gbp)}
              icon="wallet-outline"
              iconColor={Colors.primary}
            />
            <Divider />
            <Row
              label="Deductions"
              value={`− ${formatGBP(record.total_deductions_gbp)}`}
              icon="remove-circle-outline"
              iconColor={Colors.error}
            />
            <Divider />
            <Row
              label="Net Zakatable"
              value={formatGBP(record.net_zakatable_gbp)}
              icon="calculator-outline"
              iconColor={Colors.info}
              bold
            />
            <Divider />
            <Row
              label={`Nisab (${record.nisab_type_used})`}
              value={formatGBP(record.nisab_value_gbp)}
              icon="scale-outline"
              iconColor={Colors.textSecondary}
            />
          </Card>

          {/* ── Zakat due ── */}
          <Card padding="base" style={{ gap: Spacing.md }}>
            <Text style={styles.sectionTitle}>Zakat Due</Text>
            <View style={styles.zakatDueRow}>
              <View style={styles.zakatDueLeft}>
                <Text style={styles.zakatFormula}>
                  {formatGBP(record.net_zakatable_gbp)} × 2.5%
                </Text>
                <Text style={styles.zakatFormulaNote}>Net zakatable × Zakat rate</Text>
              </View>
              <Text style={styles.zakatDueAmount}>{formatGBP(record.zakat_due_gbp)}</Text>
            </View>
          </Card>

          {/* ── Islamic context ── */}
          <Card padding="base" style={{ gap: Spacing.sm }}>
            <Text style={styles.sectionTitle}>Islamic Reference</Text>
            <Text style={styles.hadithText}>
              "And establish prayer and give Zakat, and whatever good you put forward for yourselves — you will find it with Allah."
            </Text>
            <Text style={styles.hadithRef}>Al-Quran 2:110</Text>
          </Card>
        </ScrollView>
      )}
    </View>
  );
}

function Row({
  label,
  value,
  icon,
  iconColor,
  bold,
}: {
  label: string;
  value: string;
  icon: keyof typeof Ionicons.glyphMap;
  iconColor: string;
  bold?: boolean;
}) {
  return (
    <View style={rowStyles.row}>
      <Ionicons name={icon} size={16} color={iconColor} />
      <Text style={[rowStyles.label, bold && rowStyles.labelBold]}>{label}</Text>
      <Text style={[rowStyles.value, bold && rowStyles.valueBold]}>{value}</Text>
    </View>
  );
}

function Divider() {
  return <View style={{ height: StyleSheet.hairlineWidth, backgroundColor: Colors.divider }} />;
}

const rowStyles = StyleSheet.create({
  row: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm },
  label: { flex: 1, fontSize: Typography.sm, color: Colors.textSecondary },
  labelBold: { color: Colors.textPrimary, fontWeight: Typography.semibold },
  value: { fontSize: Typography.sm, fontWeight: Typography.medium, color: Colors.textPrimary },
  valueBold: { fontSize: Typography.base, fontWeight: Typography.bold, color: Colors.primary },
});

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.background },

  navBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: Spacing.base,
    paddingVertical: Spacing.md,
    backgroundColor: Colors.surface,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Colors.border,
  },
  backBtn: { flexDirection: 'row', alignItems: 'center', gap: 2, width: 80 },
  backLabel: { fontSize: Typography.base, color: Colors.primary },
  navTitle: { fontSize: Typography.base, fontWeight: Typography.semibold, color: Colors.textPrimary },
  shareBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: Colors.primaryMuted,
    alignItems: 'center',
    justifyContent: 'center',
  },

  content: { padding: Spacing.base, gap: Spacing.base },

  hero: {
    alignItems: 'center',
    paddingVertical: Spacing.xl,
    gap: Spacing.xs,
  },
  heroIcon: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: Colors.accentLight,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: Spacing.sm,
  },
  heroYear: { fontSize: Typography.xxl, fontWeight: Typography.bold, color: Colors.textPrimary },
  heroDate: { fontSize: Typography.sm, color: Colors.textSecondary },
  heroAmount: { fontSize: Typography.xxxl, fontWeight: Typography.bold, color: Colors.accent, marginTop: Spacing.sm },
  heroLabel: { fontSize: Typography.sm, color: Colors.textSecondary, textTransform: 'uppercase', letterSpacing: 0.5 },

  sectionTitle: {
    fontSize: Typography.xs,
    fontWeight: Typography.semibold,
    color: Colors.textSecondary,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },

  zakatDueRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  zakatDueLeft: { gap: 2 },
  zakatFormula: { fontSize: Typography.base, fontWeight: Typography.semibold, color: Colors.textPrimary },
  zakatFormulaNote: { fontSize: Typography.xs, color: Colors.textTertiary },
  zakatDueAmount: { fontSize: Typography.xxl, fontWeight: Typography.bold, color: Colors.accent },

  hadithText: {
    fontSize: Typography.sm,
    color: Colors.textSecondary,
    lineHeight: 20,
    fontStyle: 'italic',
  },
  hadithRef: { fontSize: Typography.xs, color: Colors.textTertiary, textAlign: 'right' },

  notFound: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: Spacing.base },
  notFoundText: { fontSize: Typography.base, color: Colors.textSecondary },
});
